from enum import Enum

class APIMethod(str, Enum):
    
    # Authentication
    AUTH = "AUTH"
    REGISTER = "REGISTER"
    
    # Friendship
    SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST"
    ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST"
    REJECT_FRIEND_REQUEST = "REJECT_FRIEND_REQUEST"
    GET_FRIENDS = "GET_FRIENDS"
    GET_PENDING_REQUESTS = "GET_PENDING_REQUESTS"
    
    # Group
    CREATE_GROUP = "CREATE_GROUP"
    ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP"
    UPDATE_GROUP_NAME = "UPDATE_GROUP_NAME"
    LEAVE_GROUP = "LEAVE_GROUP"
    DELETE_GROUP = "DELETE_GROUP"
    GET_USER_GROUPS = "GET_USER_GROUPS"
    GET_GROUP_DETAILS = "GET_GROUP_DETAILS"
    GET_GROUP_MEMBERS = "GET_GROUP_MEMBERS"

    # Message
    SEND_GROUP_MESSAGE = "SEND_GROUP_MESSAGE"
    GET_GROUP_MESSAGES = "GET_GROUP_MESSAGES"
    SEND_PRIVATE_MESSAGE = "SEND_PRIVATE_MESSAGE"
    GET_PRIVATE_MESSAGES = "GET_PRIVATE_MESSAGES"
    SEND_MESSAGE = "SEND_MESSAGE"
    GET_RECENT_MESSAGES = "GET_RECENT_MESSAGES"
